* Tasks
** DONE Implement zw3rks Cross Compilation Tutorials
   CLOSED: [2021-12-20 Mon 12:18]
   Results: [[file:CrossCompilationBlogTutorial/]]
*** DONE Android
    CLOSED: [2021-12-17]
    - Binary cross compiler not available on http://hackage.mobilehaskell.org/
*** DONE iOS
    CLOSED: [2021-12-17]
    - Installed xcode.
    - Downloaded cross compiler.
    - Created scripts.
    - Downloaded libraries for machine.
    - Compiled statically linked archive file of the HS library.
    - Setup xcode to link app.
    - Ran app.
      
** IN_PROGRESS Compile Haskell with libraries, using most straightforward approach
Using cabal and cross-compilation flags.
https://log.zw3rk.com/posts/2017-05-17-the-haskell-cabal-and-cross-compilation/
https://github.com/ghc-ios/ghc-ios-scripts

Morritz tool-chain wrapper has the wrapped ld, clang, it also has cabal, so no need to use ghc-ios-scripts.
*** DONE Create a HTTP request with a haskell HTTP library
    CLOSED: [2021-12-20 Mon 16:41]
    [[file:CrossCompilationBlogTutorial/iOSProjectCabal/]]
*** TODO Perfrom SQLite operations with Haskell SQLite library
** UNREFINED_TASK Create a 'compiling a cross compiler for mobile' Wiki entry.
*** UNREFINED_TASK Things involved when compiling Haskell and what are the relevant steps for cross compile for a platform.
** UNREFINED_TASK Create/Gather scripts for compiling a cross compiler.
** UNREFINED_TASK Create a 'dealing with Template Haskell' Wiki entry.
** UNREFINED_TASK Create a 'using Haskell libraries' Wiki entry.
** UNREFINED_TASK Create a 'common OS Haskell interop patches' Wiki entry, detailing how to patch a library to work for mobile.
** UNREFINED_TASK Create a 'Worflow for compiling and developing mobile Haskell projects' wiki entry.
** UNREFINED_TASK Create scripts for compiling and developing mobile Haskell projects.
** UNREFINED_TASK Create Github CI workflow for compiling projects.
** UNREFINED_TASK Create nix expression for compiling cross compilers.
** UNREFINED_TASK Create nix cache service for Haskell mobile packages and compilers.   
