* Tasks
** DONE Implement zw3rks Cross Compilation Tutorials
   CLOSED: [2021-12-20 Mon 12:18]
   Results: [[file:CrossCompilationBlogTutorial/]]
*** DONE Android
    CLOSED: [2021-12-17]
    - Binary cross compiler not available on http://hackage.mobilehaskell.org/
*** DONE iOS
    CLOSED: [2021-12-17]
    - Installed xcode.
    - Downloaded cross compiler.
    - Created scripts.
    - Downloaded libraries for machine.
    - Compiled statically linked archive file of the HS library.
    - Setup xcode to link app.
    - Ran app.
      
** DONE Compile Haskell with libraries, using most straightforward approach
   CLOSED: [2021-12-21 Tue 12:26]
Using cabal and cross-compilation flags.
https://log.zw3rk.com/posts/2017-05-17-the-haskell-cabal-and-cross-compilation/
https://github.com/ghc-ios/ghc-ios-scripts

Morritz tool-chain wrapper has the wrapped ld, clang, it also has cabal, so no need to use ghc-ios-scripts.

Seems like need patched ld to link against the mobile OS libraries.

Package resolver quite essential for wide range of users.
*** DONE Create a HTTP request with a haskell HTTP library.
    CLOSED: [2021-12-20 Mon 16:41]
    [[file:CrossCompilationBlogTutorial/iOSProjectCabal/]]
*** DONE Perfrom SQLite operations with Haskell SQLite library.
    CLOSED: [2021-12-21 Tue 12:26]
    - Adding the 'sqlite' library fails to compile due to an ambiguos function usage error (with a function (namely <>) from base). 
    - Although when compiling for a newer ghc, it doesn't get that error. This could be because cabal used a base for ghc 8.4.0 that was different for  ghc 8.10.0.

    - Seems vital to be able to have flexible ghc versions so that it can integrate fully with the package resolver eco system.
    - Got 'direct-sqlite' to compile and link. Although haven't properly tried creating a database, but for now assuming that it's enough.
*** DONE Attempt to compile simplex libraries and observe blocks.
    CLOSED: [2021-12-21 Tue 12:26]
    - https://github.com/simplex-chat/simplexmq/tree/v5-ghc844
      - This branch is made to be compatible with GHC 8.4.4
      - The .cabal file generated for this stack project does not compile for GHC 8.4.0
	- Manually trying to change the .cabal file to work is extremely time consuming, a lot of version conflicts.
      - A stack LTS reslover for GHC 8.4.0 didn't exist, so an older version of the resolver was used but that still caused problems, namely with the hand pinned versions of the packages.
	- Maybe with a bit of effort, can port it down to GHC 8.4.0.
	- But can see that would be much more freeing having an arbitrary version of the GHC compiler available.
    - https://github.com/simplex-chat/simplex-chat
      - GHC version 8.4.0 does not support BlockArguments
    - I havan't gotten to the point of the error, but there it's highly likely that template haskell would stop me from compiling the project as well.
      

** IN_PROGRESS Compling GHC Cross Compiler of arbitrary versions
*** IN_PROGRESS Compile a GHC Cross Compiler of arbitrary versions
- Understand the process of compilation through the blogs [[file:notes.org::*zw3rk Blog][zw3rk Blog]]. 
- Create/Gather scripts for compiling a cross compiler.
*** UNREFINED_TASK Create a 'compiling a cross compiler for mobile' Wiki entry.
- Things involved when compiling Haskell and what are the relevant steps for cross compile for a platform.

** IN_PROGRESS Handle Template Haskell
*** IN_PROGRESS Implement zw3rk template haskell solutions for iOS.
*** TODO Implement zw3rk template haskell solutions for Android.
*** UNREFINED_TASK Create a 'dealing with Template Haskell' Wiki entry.

** UNREFINED_TASK Create a 'using Haskell libraries' Wiki entry.
** UNREFINED_TASK Create a 'common OS Haskell interop patches' Wiki entry, detailing how to patch a library to work for mobile.
** UNREFINED_TASK Create a 'Worflow for compiling and developing mobile Haskell projects' wiki entry.
** UNREFINED_TASK Create scripts for compiling and developing mobile Haskell projects.
** UNREFINED_TASK Create Github CI workflow for compiling projects.
** UNREFINED_TASK Create nix expression for compiling cross compilers.
** UNREFINED_TASK Create nix cache service for Haskell mobile packages and compilers.   
